name: "YTuner"
description: "vTuner internet radio replacement for AVR devices and Libratone speakers"
version: "1.0.3"
slug: "ytuner"
url: "https://github.com/Jarvichi/ha-addon-ytuner"
arch:
  - aarch64
  - amd64
init: false
startup: services
boot: auto
host_network: true
ports:
  80/tcp: 80
  8080/tcp: 8080
  8888/tcp: 8888
ports_description:
  80/tcp: "HTTP - AVR devices connect here"
  8080/tcp: "Web management UI"
  8888/tcp: "Transcoding proxy"
webui: "http://[HOST]:[PORT:8080]"
ingress: true
ingress_port: 8080
panel_icon: "mdi:radio"
panel_title: "YTuner"
map:
  - share:rw
options:
  transcode_bitrate: "192k"
  transcode_max_concurrent: 4
  log_level: "info"
schema:
  transcode_bitrate: str
  transcode_max_concurrent: "int(1,16)"
  log_level: "list(none|info|warning|error|debug)"
